# Setup
title: Arya Notes
description: Notes for engineering journey and hobbies related
url: https://ryawcksn.github.io
avatar: /gao.png
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - vendor

# Optimize Jekyl SEO Tag
twitter:
  username: r_wcksn
  card: summary
logo: logo.png
social:
  name: Pramudya Arya Wicaksana
  links:
    - https://twitter.com/r_wcksn
    - https://github.com/RyaWcksn
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Pramudya Arya Wicaksana
  url: https://github.com/RyaWcksn
  email: pram.aryawcksn@yuuriya.tech

